spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
#    url: jdbc:mysql://192.168.2.218:3306/sell?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://192.168.2.150:3306/mysell?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false

jpa:
    show-sql: true

server:
  context-path: /sell